spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/WebAppBoard
    url: jdbc:log4jdbc:mysql://localhost:3306/WebAppBoard
    username: boardServerDev
    password: ${db.password}
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  servlet:
    multipart:
      location: ${user.dir}/SpringMybatisBoard20210327/src/main/resources/static/public/img
      max-file-size: 1MB
      max-request-size: 5MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: develckmtest@gmail.com
    password: ${email.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
img:
  upload:
    path: ${user.dir}/SpringMybatisBoard20210327/src/main/resources/static/public/img

static:
  path: ${user.dir}/SpringMybatisBoard20210327/src/main/resources/static

server:
  port: 8080
mybatis:
  type-aliases-package: com.acorn.springboardteacher.dto
  mapper-locations: mapper/*Mapper.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true