spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/WebAppBoard
    url: jdbc:log4jdbc:mysql://localhost:3306/WebAppBoard
    username: boardServerDev
    password: mysql123
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
server:
  port: 8080
mybatis:
  type-aliases-package: com.acorn.springboardteacher.dto
  mapper-locations: mapper/*Mapper.xml
